apiVersion: v1
kind: Pod







metadata: 
    name: myapp-pod
    labels:
      app: myapp
spec:
  containers:
    - name: nginx-f
      image: nginx
      resources:
      limits:
        cpu: "1"
      requests:
        cpu: "0.5"
    args:
    - -cpus
    - "2"
    - name: redis-b
      image: redis
      resources:
      limits:
        cpu: "1"
        memory: 200Mi
      requests:
        cpu: "0.5"
    args:
    - -cpus
    - "2"